---
name: paasta-portal-ui                      # 서비스 배포이름(필수) bosh deployments 로 확인 가능한 이름

stemcells:
- alias: ((stemcell_alias))
  os: ((stemcell_os))
  version: ((stemcell_version))

releases:
- name: "((releases_name))"                   # 서비스 릴리즈 이름(필수) bosh releases로 확인 가능
  version: latest                                              # 서비스 릴리즈 버전(필수):latest 시 업로드된 서비스 릴리즈 최신버전

update:
  canaries: 1                                               # canary 인스턴스 수(필수)
  canary_watch_time: 5000-120000                            # canary 인스턴스가 수행하기 위한 대기 시간(필수)
  update_watch_time: 5000-120000                            # non-canary 인스턴스가 수행하기 위한 대기 시간(필수)
  max_in_flight: 1                                          # non-canary 인스턴스가 병렬로 update 하는 최대 개수(필수)
  serial: false

instance_groups:
########## INFRA ##########
- name: mariadb
  azs:
  - z6
  instances: 1
  vm_type: "((vm_type_small))"
  stemcell: "((stemcell_alias))"
  persistent_disk_type: "((mariadb_disk_type))"
  networks:
  - name: ((internal_networks_name))
  jobs:
  - name: mariadb
    release: "((releases_name))" 
  syslog_aggregator: null

- name: haproxy
  azs:
  - z7
  instances: 1
  vm_type: "((vm_type_tiny))"
  stemcell: "((stemcell_alias))"
  networks:
  - name: ((internal_networks_name))
  - name: ((external_networks_name))
    static_ips: ((haproxy_public_ip))
  jobs:
  - name: haproxy
    release: "((releases_name))"
  syslog_aggregator: null
  properties:
    infra:
      admin:
        enable: "((infra_admin))"

######## WEB SERVICE ########

- name: paas-ta-portal-webadmin
  azs:
  - z6
  instances: 1
  vm_type: "((vm_type_small))"
  stemcell: "((stemcell_alias))"
  networks:
  - name: ((internal_networks_name))
  jobs:
  - name: paas-ta-portal-webadmin
    release: "((releases_name))"
  syslog_aggregator: null
  properties:
    java_opts: "-Xmx450m -Xss1M -XX:MaxMetaspaceSize=93382K -XX:ReservedCodeCacheSize=240m -XX:+UseCompressedOops -Djdk.tls.ephemeralDHKeySize=2048 -Dfile.encoding=UTF-8 -XX:+UseConcMarkSweepGC -XX:SoftRefLRUPolicyMSPerMB=50 -Dsun.io.useCanonCaches=false -Djava.net.preferIPv4Stack=true -XX:+HeapDumpOnOutOfMemoryError -XX:-OmitStackTraceInFastThrow -Xverify:none -XX:ErrorFile=/var/vcap/sys/log/java_error_in_idea_%p.log -XX:HeapDumpPath=/var/vcap/sys/log/java_error_in_idea.hprof"
    api:
      url: "((default_portal_api_url))"
    port: 8090

- name: paas-ta-portal-webuser
  azs:
  - z6
  instances: 1
  vm_type: "((vm_type_tiny))"
  stemcell: "((stemcell_alias))"
  networks:
  - name: ((internal_networks_name))
  jobs:
  - name: paas-ta-portal-webuser
    release: "((releases_name))"
  syslog_aggregator: null
  properties:
    logPath: "/var/vcap/sys/log/paas-ta-portal-webuser"   # WEBUSER는 아파치를 사용함, APACHE 로그 위치
    webDir: "/var/vcap/packages/apache2/htdocs"           # WEBUSER는 아파치를 사용함, APACHE 웹 디렉토리 설정
    cf:
      uaa:
        clientsecret: ((portal_client_secret))
    monitoring: ((portal_webuser_monitoring))
    quantity: ((portal_webuser_quantity))
    automaticApproval: ((portal_webuser_automaticapproval))

properties:
  mariadb:                                                # MARIA DB SERVER 설정 정보
    port: ((mariadb_port))                                            # MARIA DB PORT 번호
    admin_user:
      password: '((mariadb_user_password))'                             # MARIA DB ROOT 계정 비밀번호
    host_names:
    - mariadb0
  portal_default:
    name: "((default_portal_api_name))"
    url: "((default_portal_api_url))"
    uaa_url: "((default_portal_uaa_url))"
    header_auth: "((default_portal_header_auth))"
    desc: "((default_portal_api_desc))"
  cf_api_version: "((cf_api_version))"
  webadmin_ips: "((haproxy_public_ip))"
